### ISSUE TITLE
Total DPS or Damage isn't showing

### ISSUE THREAD

**Issue by codeduph** [bkader/Skada-WoTLK#100]
**Describe the bug**
Total DPS or Damage isn't showing

![2023-01-24_163618](https://user-images.githubusercontent.com/16449014/214246361-998cdc90-5009-4913-8d51-53e387d4db9e.png)

Vids: https://streamable.com/b3if0e

it only show current fight.... But the total damage is empty or not showing....

Skada Damage Meter (Revisited) 1.8.84-4
WoW Wrath of the Lich King Classic Versions 3.4.1

**Comment by bkader** [comment]
Since **1.8.77**

https://user-images.githubusercontent.com/4732702/214353042-8ef72ff3-0d44-4610-b32a-752af96a6909.mp4

Please report issues of retail or classic wrath on their own repo [**here**](https://github.com/bkader/Skada-Damage-Meter)
