### ISSUE TITLE
Resets logs after death

### ISSUE THREAD

**Issue by Furyzcx** [bkader/Skada-WoTLK#101]
It dumps the logs after death/entry into inst/leaving the group. It began after the last update. Despite the fact that everything was put up to not drop it, but asked before the entrance, leaving the group, etc. The pseudonym also does not work. He writes in a chat that you can use symbols and two gaps. Although I write any words without numbers, etc.

**Comment by Furyzcx** [comment]
WowCircle
The latest version breaks all addons, the photo shows an example of Prat and SexyMap:
https://i.paste.pics/0d90793b77e15c1ad2cc402125bdc2ce.png

Delete Skada:
https://i.paste.pics/ae6cbee25969a2a12b36dcd0f31d4dc6.png

**Comment by bkader** [comment]
Names addons that were broken by Skada, **all addons** doesn't help locate the issue. Also, I am afraid I couldn't understand the first comment.

**Comment by Furyzcx** [comment]
In general, the first comment. Resets all Skada data after each death. Reset is disabled in settings.

**Comment by bkader** [comment]
@Furyzcx try with Skada only, then enable addons one by one until you find the one causing the conflict. We'll see from there.

**Comment by bkader** [comment]
Closing the issue because of the lack of info.
