### ISSUE TITLE
Can't embed Skada into ELVUI panel.

### ISSUE THREAD

**Issue by ZhengYuan-Public** [bkader/Skada-WoTLK#111]
**Describe the bug**
I am using the latest version of [Skada-WoTLK](https://github.com/bkader/Skada-WoTLK) and [ELVUI-WoTLK](https://github.com/ElvUI-WotLK/ElvUI). 

While using a fairly old version of Skada from [here](https://www.curseforge.com/wow/addons/skada/files?version=3.3.3), the UI was working well with the backported ELVUI. 

But the [Skada-WoTLK](https://github.com/bkader/Skada-WoTLK) does not embed into ELVUI panels correctly. The width of the Skada frame does change accordingly with either single or dual embed, but the frame is not working properly.

I'm not sure if the problem is with Skada or ELVUI. While searching for the question in Google, it seems the `tukui.org` used to have a post related, but the forum is no longer available so I couldn't find any useful info.

![微信截图_20230614114558](https://github.com/bkader/Skada-WoTLK/assets/9320285/3d1d33d7-717b-444b-95a8-bfbbf09e7aeb)

**To Reproduce**
`Esc` -> ELVUI -> Addon Skin -> Embed Settings -> Embed Type -> Select Skada

**Comment by bkader** [comment]
Hello @ZhengYuan-Public 
If you are using this version of [Skada](https://github.com/bkader/Skada-WoTLK), the latest version of [ElvUI](https://github.com/ElvUI-WotLK/ElvUI) as well as [ElvUI_AddOnSkins](https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins) everything should work just fine.

https://github.com/bkader/Skada-WoTLK/assets/4732702/079137f2-2897-4a04-89ad-0722d5f4e2d0

_If you still cannot make it work then you can open this issue again (just make sure to have latest versions of each addon)._
