### ISSUE TITLE
"Total" segment showing only oveall data

### ISSUE THREAD

**Issue by KuroiMatoO** [bkader/Skada-WoTLK#112]
**Describe the bug**
As the title suggests - it's impossible to check for example total damage spell by spell. It only shows overall damage by the player or any other source.

**To Reproduce**
1. Install addon
2. Choose "total" segment
3. Choose "Damage"
4. Hit someone with a stick (preferably inside a game)
5. Click on any bar inside the "Damage" category using left mouse button
6. Nothing happens

**Expected behavior**
When you click on any bar inside "damage" it should open spell breakdown just like it does with "current segment"

**Video**

https://github.com/bkader/Skada-WoTLK/assets/2721793/dd001422-3c6d-4157-8528-7372e29052e4
(video is not working on my side for some reason so, there is a youtube link - https://youtu.be/WrucQdcmv2o )

**Additional context**
Maybe I'm just stupid and missed something, but I checked the settings multiple times trying to find such option. And yes, I've deleted saved variables before install. Also since I wasn't sure if it's an actual bug or this is intended feature I put it into bugs. If it is intended please move it to feature request.

**Comment by bkader** [comment]
duplicate #100

**Comment by KuroiMatoO** [comment]
Ok, sorry. I'm stupid after all lol. 
Thanks for the great addon, buddy!
