### ISSUE TITLE
Fury of Frostmourne triggers modules to change to wipe mode

### ISSUE THREAD

**Issue by wojas007** [bkader/Skada-WoTLK#36]
Hey!
I'm only making this to remember about this:
![image](https://user-images.githubusercontent.com/55255393/107280520-bf0e8c00-6a58-11eb-8be0-8ea63cfa5fe8.png)

**Comment by bkader** [comment]
Despite the idea not being bad, the fight technically ends at `Fury of Frostmourne`. After the RP, nothing matters.
Even if I was hyped to add it, it sadly won't be implemented.

**Comment by bkader** [comment]
If people have set the wipe mode option and don't want `Fury of Frostmourne` to be considered as a wipe, you can add the following lines at the combat of `Skada:CombatLogEvent` function (_needs to be tested_):
```lua
if select(1, ...) == 72350 then
	for _, win in Skada:IterateWindows() do
		if win.db.wipemode ~= "" then
			local wipemode = win.db.wipemode
			win.db.wipemode = ""
			self.After(2, function() win.db.wipemode = wipemode end)
		end
	end
end
```
