### ISSUE TITLE
Wrong spells shown in chat

### ISSUE THREAD

**Issue by CraftedRO** [bkader/Skada-WoTLK#45]
Skada version 18.45
As you can see in my screehshoot it does show wrong casted spells like Cheap Shot from Death Knight and Teleport Monastery from Dk pet ghoul .

![WoWScrnShot_051421_153746](https://user-images.githubusercontent.com/24683355/118339325-2db02980-b521-11eb-88ce-4c00c587ed35.jpg)

**Comment by bkader** [comment]
This was fixed. Please try to update the addon and check again.

**Comment by CraftedRO** [comment]
well I got the master branch latest version with latest updates from 4 days old , If I remember well in latest realeased version this doesn't even appear in chat like that at all .

**Comment by bkader** [comment]
What's the version number you are using?

**Comment by CraftedRO** [comment]
1.8.45 or 18.45 I guess both are correct :)
![Capturez](https://user-images.githubusercontent.com/24683355/118340110-7bc62c80-b523-11eb-9541-bfd1dcd6ff20.JPG)

**Comment by CraftedRO** [comment]
Another proof right now in Icecrown I tested .

![WoWScrnShot_051521_023043](https://user-images.githubusercontent.com/24683355/118340837-a618e980-b525-11eb-851a-3b6fb213d4f8.jpg)

**Comment by CraftedRO** [comment]
anywaw this first hit thing its annoyng and useless , idk its implemented in official updated skada from retail ?

**Comment by bkader** [comment]
The addon has been updated.
The `First Hit` _should_ no longer be spammy and it can even be disabled in `General options`.
If it works like intended you can close this issue.

**Comment by CraftedRO** [comment]
seems ok now.
