### ISSUE TITLE
LibFail-1.0.lua

### ISSUE THREAD

**Issue by husker3011** [bkader/Skada-WoTLK#48]
Date: 2021-06-02 04:39:50
ID: -1
Error occured in: Global
Count: 1
Message: ...erface\AddOns\Skada\Libs\LibFail-1.0\LibFail-1.0.lua line 2261:
   attempt to compare number with table
Debug:
   [C]: ?
   ...erface\AddOns\Skada\Libs\LibFail-1.0\LibFail-1.0.lua:2261:
      ...erface\AddOns\Skada\Libs\LibFail-1.0\LibFail-1.0.lua:2256
   ...erface\AddOns\Skada\Libs\LibFail-1.0\LibFail-1.0.lua:847:
      ...erface\AddOns\Skada\Libs\LibFail-1.0\LibFail-1.0.lua:832
AddOns:
  Swatter, v5.8.4723 (CreepyKangaroo)
  Ace3, v
  AtlasLoot, vv5.11.04a
  AtlasLootFu, vv5.11.04
  DBMCore, v
  ElvUI, v6.08
  GearScoreLite, v3x04
  LootCouncilLite, v1.011
  Omen, v3.0.9
  Quartz, v3.0.3.1
  RaidBuffStatus, vv3.274
  Skada, v1.8.50
  SlideBar, v5.8.4723 (CreepyKangaroo)
  SnowfallKeyPress, v
  Stubby, v5.8.4723 (CreepyKangaroo)
  WeakAuras, v3.2.3
  BlizRuntimeLib_enUS v3.3.5.30300 <logon.whitemane.gg>
  (ck=1a9)

**Comment by bkader** [comment]
Hello @husker3011 and thanks for reporting the issue.
Unfortunately, the problem seems to be caused by another addons that's using `LibFails-1.0` and that's loaded before Skada. Probably EnsidiaFails or a similar addon (_addons are loaded alphabetically_).
```lua
-- Vezax Mark of the Faceless
if self.LastEvent.Fail_Vezax_Leech > self.VEZAX_LEECH_THRESHOLD then --< line 2261
    self:FailEvent("Fail_Vezax_Leech", self.VezaxLeechTarget, self.FAIL_TYPE_NOTMOVING)
    self.LastEvent.Fail_Vezax_Leech = 0
end
```
At least, that's what the error says.

**Comment by husker3011** [comment]
Another lua error
Date: 2021-06-02 15:09:31
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Skada\Skada.lua line 1580:
   bad argument #1 to 'band' (number expected, got string)
Debug:
   [C]: ?
   [C]: ?
   Skada\Skada.lua:1580: IsCreature()
   Skada\Skada.lua:1571: IsBoss()
   Skada\Skada.lua:196:
      Skada\Skada.lua:172
   Skada\Modules\Enemies.lua:319: Update()
   Skada\Skada.lua:1791: AddSubviewToTooltip()
   Skada\Skada.lua:1834: ShowTooltip()
   Skada\BarDisplay.lua:408:
      Skada\BarDisplay.lua:404
AddOns:
  Swatter, v5.8.4723 (CreepyKangaroo)
  Ace3, v
  AtlasLoot, vv5.11.04a
  AtlasLootFu, vv5.11.04
  DBMCore, v
  ElvUI, v6.08
  GearScoreLite, v3x04
  LootCouncilLite, v1.011
  Omen, v3.0.9
  Quartz, v3.0.3.1
  RaidBuffStatus, vv3.274
  Skada, v1.8.50
  SlideBar, v5.8.4723 (CreepyKangaroo)
  SnowfallKeyPress, v
  Stubby, v5.8.4723 (CreepyKangaroo)
  WeakAuras, v3.2.3
  BlizRuntimeLib_enUS v3.3.5.30300 <logon.whitemane.gg>
  (ck=1a9)
