### ISSUE TITLE
Skada and ElvUI_Enhanced

### ISSUE THREAD

**Issue by Frixen** [bkader/Skada-WoTLK#49]
Please add Skada report compatibility for
https://github.com/ElvUI-WotLK/ElvUI_Enhanced/blob/master/ElvUI_Enhanced/Modules/Chat/DPSLinks.lua

**Comment by bkader** [comment]
Hello @Frixen. This was fixed but not yet pushed. It will be fixed on the next update asap.

**Comment by Frixen** [comment]
> Hello @Frixen. This was fixed but not yet pushed. It will be fixed on the next update asap.

Ty:)

**Comment by Frixen** [comment]
До сих пор не работает, Элвуи не обрабатывает спам от Скада. Вот как это должно работать:
![image](https://user-images.githubusercontent.com/18544029/121785636-dbccf300-cbf5-11eb-9e1b-5a371ac434b9.png)

**Comment by bkader** [comment]
@Frixen it is sadly a problem with **ElvUI_Enhanced** _DPSLinks.lua_ file and not Skada.
You can fix this by editing the file `ElvUI_Enhanced\Modules\Chat\DPSLinks.lualua`:
```lua
local spamFirstLines = {
	"^Recount - (.*)$",				-- Recount
	"^Skada: (.*) for (.*):$",		-- Skada enUS
	"^Skada: (.*) por (.*):$",		-- Skada esES/ptBR
	"^Skada: (.*) für (.*):$",		-- Skada deDE
--	"^Skada: (.*) fur (.*):$",		-- Skada deDE
	"^Skada: (.*) pour (.*):$",		-- Skada frFR
	"^Skada: (.*) для (.*):$",		-- Skada ruRU
--	"^Skada: (.*) per (.*):$",		-- Skada itIT
	"^(.*) 의 Skada 보고 (.*):$",	-- Skada koKR
	"^Отчёт Skada: (.*), с (.*):$",	-- Skada ruRU
	"^Skada报告(.*)的(.*):$",		-- Skada zhCN
	"^Skada:(.*)來自(.*):$",			-- Skada zhTW
	"^(.*) Done for (.*)$",			-- TinyDPS
	"^Details!:(.*)$" -- Details!
}

local spamNextLines = {
	"^(%d+)%. (.*)$",	-- Recount, Skada
	"^ (%d+). (.*)$",	-- Skada
	"^(%d+). (.*)$", -- Recount, Details! and Skada
	"^(.*)  (.*)$", -- Additional Skada
	"^.*%%%)$",			-- Skada player details
	"^(%d+). (.*):(.*)(%d+)(.*)(%d+)%%(.*)%((%d+)%)$", -- TinyDPS
}
```

**Comment by Barsoomx** [comment]
```
	"^(%d+). (.*)$", -- Recount, Details! and Skada
	"^(.*)  (.*)$", -- Additional Skada
```
we figured those are not needed, only the localisation part. I'll merge it into elvui-enhanced repo...
