### ISSUE TITLE
Skada makes my Gnosis addon not working

### ISSUE THREAD

**Issue by mzich** [bkader/Skada-WoTLK#50]
Hey, when I turn on this modified Skada, my Gnosis (castbar addon) stops working. When I use normal Skada for 3.3.5, this bug does not appear.  Could you please fix it or tell me some hotfix?
I also attach two screenshots showing exactly the same situation with Skada on/off.
![image](https://user-images.githubusercontent.com/80593666/121766782-ae7c3880-cb54-11eb-9a94-26276ecd05d8.png)
![image](https://user-images.githubusercontent.com/80593666/121766823-dec3d700-cb54-11eb-8f2b-239208b6ee70.png)

**Comment by bkader** [comment]
Hi. Can you at least turn on LUA errors and see if there is any?

**Comment by mzich** [comment]
> Hi. Can you at least turn on LUA errors and see if there are any?

There are no LUA errors.

**Comment by bkader** [comment]
Sadly, it's Gnosis that's making other addons bug, not just Skada.
