### ISSUE TITLE
SkadaRev libs and skin

### ISSUE THREAD

**Issue by Barsoomx** [bkader/Skada-WoTLK#51]
Skins may be removed from the repo after https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins/pull/155 is merged into the main repo

**Comment by Frixen** [comment]
> Skins may be removed from the repo after [ElvUI-WotLK/ElvUI_AddOnSkins#155](https://github.com/ElvUI-WotLK/ElvUI_AddOnSkins/pull/155) is merged into the main repo

ty

**Comment by Barsoomx** [comment]
cf0f4f9
