### ISSUE TITLE
Class Icons Are Missing

### ISSUE THREAD

**Issue by Noob1e** [bkader/Skada-WoTLK#52]
![WoWScrnShot_061921_115735](https://user-images.githubusercontent.com/27544010/122637133-bd835d80-d0f5-11eb-92c5-243f1fd9de8b.jpg)
After the latest update class icons have turned into red squares and bar colors are all blue now.
Also, I was only using damage done but now meter shows "DPS" and "%" too. I couldn't fix that.

**Comment by Noob1e** [comment]
I deleted "SkadaImprovement.lua" and "SkadaImprovement.lua.bak" in WTF folder and everything is fine for now.

**Comment by Noob1e** [comment]
It's back to the red again after logging out.

**Comment by bkader** [comment]
I found the issue. It should work fine.
Class icons decralation was moved from `OnInitialize` to `OnEnable`, this is what caused them to not be loaded for other modules.
I moved them back to the `OnInitialize` function and it should work fine. Just get the content of the main `Skada.lua` file.

**Comment by bkader** [comment]
@Noob1e for DPS and % please check the "Columns" settings. You simply uncheck `Percent` for `Damage` module.
