### ISSUE TITLE
Any way to export a current fight segment into a .txt file?

### ISSUE THREAD

**Issue by Pocokk** [bkader/Skada-WoTLK#53]
Greetings,

I know it sounds weird, but is there any way to save a fight's Skada report out of the game somehow? Where should I look at, is it saved in the WTF folder? Also I presume it won't contain names, just strings/HEX ids for the spells and such, is there a way to convert those?

**Comment by bkader** [comment]
Hello @Pocokk.
Skada export was and still a work in progress to find a better way to export data. It might be added soon, it really depends.
And yes, everything is saved to a lua file inside character's `SavedVariables`.
As for spells and stuff, why do you need to convert them anyways? Send the lua to someone, they drop it and can easily check the segment, but they loose their data.
We'll see if the export works fine it will be added.

**Comment by Pocokk** [comment]
> 
> 
> Hello @Pocokk.
> Skada export was and still a work in progress to find a better way to export data. It might be added soon, it really depends.
> And yes, everything is saved to a lua file inside character's `SavedVariables`.
> As for spells and stuff, why do you need to convert them anyways? Send the lua to someone, they drop it and can easily check the segment, but they loose their data.
> We'll see if the export works fine it will be added.
