### ISSUE TITLE
Mark of Blood healing missing.

### ISSUE THREAD

**Issue by notkisi** [bkader/Skada-WoTLK#54]
**Describe the bug**
Mark of blood is not being tracked and attributed to DK.

**To Reproduce**
Use the spell in combat.

**Expected behavior**
Mark of Blood should show and attribute to DK's healing.

**Video**
N/A

**Additional context**
N/A

**Comment by bkader** [comment]
Any screenshots or videos? This has not been reported before. I will check.

**Comment by bkader** [comment]
This is not a bug. Please refer to this 
https://www.warmane.com/bugtracker/report/102584

**Comment by notkisi** [comment]
Then can this be considered as a feature? it is annoying not to have any insight of how much my mark of blood healing was.

**Comment by bkader** [comment]
> Then can this be considered as a feature? it is annoying not to have any insight of how much my mark of blood healing was.

It sadly cannot be and should not be considered as a feature. The healing is attributed to the enemy with the mark. Maybe you can check `Healing Taken` or `Enemy Healing Done` modules, maybe be it will appear there but no guarantee.
