### ISSUE TITLE
Windows should have separated own and global show/hide flags

### ISSUE THREAD

**Issue by GetLocalPlayer** [bkader/Skada-WoTLK#59]
https://user-images.githubusercontent.com/19322847/127183101-edad1bc4-7391-400a-a459-1494662aaa30.mp4

**Comment by bkader** [comment]
Hello @GetLocalPlayer 
Even if Skada already always you to automatically hide/show windows depending on certain situations (_solo, pvp ... etc_), it is indeed a good idea to have something manual, so I added it.
You have 3 options:
1. Ctrl+left-click on the minimap button to hide/show all windows (_it doesn't affect windows already hidden_).
2. You case use the provided commands `/skada show` or `/skada hide`
3. You can use the provided function `Skada:ShowHide()`.

Both #2 and #3 can be used as macros (_for 3rd: `/run Skada:ShowHide()`_)

**Comment by GetLocalPlayer** [comment]
Thank you.
