### ISSUE TITLE
Interface Failed Because of an Addon

### ISSUE THREAD

**Issue by Noob1e** [bkader/Skada-WoTLK#62]
```
8/15 09:55:44.327  Global variable XxQP tainted by MACRO_TAINT - XxQP="/run SendAddonMessage('2NDv','HX0m6UO','WHISPER','l0l')":1
8/15 09:55:44.327      RunScript()
8/15 09:55:44.327      ?:1
8/15 09:55:44.327  Execution tainted by MACRO_TAINT while reading XxQP - ?:1
8/15 09:55:44.327  An action was blocked because of taint from MACRO_TAINT - RunMacroText()
8/15 09:55:44.327      ?:1
8/15 10:25:20.137  An action was blocked because of taint from Skada - CancelLogout()
8/15 10:25:20.137      Interface\FrameXML\StaticPopup.lua:1506 OnHide()
8/15 10:25:20.137      Interface\FrameXML\StaticPopup.lua:3452 StaticPopup_OnHide()
8/15 10:25:20.137      StaticPopup1:OnHide()
8/15 10:25:20.137      StaticPopup1:Hide()
8/15 10:25:20.137      Interface\FrameXML\StaticPopup.lua:3286 StaticPopup_Hide()
8/15 10:25:20.137      Interface\FrameXML\UIParent.lua:578
```
I don't know how to reproduce it but I was having "Interface failed because of an addon" error. So I enabled taint logs and saw this one.
There're also 2 more errors I think (MACRO_TAINT) but I have no idea how to fix any of these.

**Comment by bkader** [comment]
Are you sure it's not an addon that's altering a library or that's providing a different library version that's causing this issue? Because unless the CancelLogout is from a library, there is no such function is Skada.

**Comment by Noob1e** [comment]
I really don't have any idea what's causing this error. I didn't get a new addon or changed anything. Just kept them updated. And as far as I know, only Skada and DBM (Zidras') got updated recently.

**Comment by Zidras** [comment]
Sorry to intrude, I also don't see any way DBM could influence this, but I can assure you it's not new. I found a forum post on warmane dated 2020: http://forum.warmane.com/showthread.php?t=423624

**Comment by bkader** [comment]
Skada updates for at least the last 10 days didn't change big things and only checks, tweaks and some minor lua errors were fixed. The error might be from an addon that's executing code before logout or when using a Cancel action/button, probably some profiles related stuff.

**Comment by bkader** [comment]
Yes @Zidras , it's a common bug that happens when using the interface options Cancel button sometimes, even without any addon enabled. That's why I said it might a profiles related issue or an addon that's reverting stuff after using the Cancel action/button, probably reverting some protected stuff.

**Comment by Noob1e** [comment]
> Sorry to intrude, I also don't see any way DBM could influence this, but I can assure you it's not new. I found a forum post on warmane dated 2020: http://forum.warmane.com/showthread.php?t=423624

Yeah, I found that as well but since I saw "Skada" in the logs, I just wanted to check if it's related with it or not. Thanks anyway :)
