### ISSUE TITLE
Something Wrong with Total Calculations?

### ISSUE THREAD

**Issue by Noob1e** [bkader/Skada-WoTLK#66]
Total healing done (damage as well) and detailed calculations doesn't match.

![WoWScrnShot_091221_225738](https://user-images.githubusercontent.com/27544010/133001132-a7891b94-f87a-4ba5-a8dd-5cbb135114de.jpg)
![WoWScrnShot_091221_225741](https://user-images.githubusercontent.com/27544010/133001135-191ca86d-eb79-4a36-b946-f20c78ce7e77.jpg)

**Comment by bkader** [comment]
It would be great if you DM me the data for that segment, or check on the next one. Oh, and on what version are you?

**Comment by Noob1e** [comment]
It's version 1.8.69 but I couldn't post the details because it didn't happen again. If it happens again, I'll reopen this report. Thanks anyway :)

**Comment by bkader** [comment]
Sure no problem. Make sure to update the addon whenever possible because changes were pushed today. Cheers!
