### ISSUE TITLE
Maximum bars setting missing?

### ISSUE THREAD

**Issue by RazorMid** [bkader/Skada-WoTLK#67]
Hello, I can't seem to find the maximum bars setting anymore which used to be present in the old skada. Is it intended or am I missing something? https://i.gyazo.com/1737a55fa26bdc8e216638a39a3bbe06.png
If it's missing would be great if you can add this option as my UI design is responsive to the number of bars.

**Comment by bkader** [comment]
Hello @RazorMid . That option isn't needed and the maximum bars is controlled by your window height.

**Comment by RazorMid** [comment]
Well, whenever I try to modify the default height it's getting reversed again to 203 after logout or reload and thus limits me on maximum 8 bars. Any idea why does this happens? I've created a new profile and everything but still no good. (using elvui in combination)

**Comment by bkader** [comment]
Is your ElvUI up to date?

**Comment by RazorMid** [comment]
Yes, it is.

**Comment by bkader** [comment]
If you're not embedding Skada to any frame then make sure to disable it for Skada on elvui addonskins

**Comment by RazorMid** [comment]
That doesn't seem to be the case, I'll try to reinstall both addons. Thanks for your time.

**Comment by bkader** [comment]
Make sure to delete old skada saved variables 8n case you didn't. It's mandatory. This problem was reported many times and the issue was always with elvui addonskins.

**Comment by RazorMid** [comment]
Yes, I did that initially prior to installing the new skada version.
