### ISSUE TITLE
Bladestorm and Whirlwind

### ISSUE THREAD

**Issue by Noob1e** [bkader/Skada-WoTLK#71]
Skada calculating Bladestorm as it is Whirlwind.

![Bladestorm](https://user-images.githubusercontent.com/27544010/140644460-146df26f-cc90-41de-8475-0ff59cc80906.png)

**Comment by bkader** [comment]
What version are you using? I am pretty sure EXTRA_ATTACKS was fixed.

**Comment by Noob1e** [comment]
## Version: 1.8.71
## X-Date: 2021-10-26 @ 00:33 AM |cff808080UTC|r

**Comment by bkader** [comment]
Alright, I will check it and it will be pushed alongside the next update when fixed. Thanks for reporting it @Noob1e

**Comment by bkader** [comment]
After testing few other addons to see if any of them tracked that, none of them did. I am afraid that's not a bug, that's how the game works.

![Screenshot_8](https://user-images.githubusercontent.com/4732702/140665341-7037d02a-b501-4938-9991-d0fcc076a720.png)

**Comment by Noob1e** [comment]
Yea, I have never thought of that. Thanks anyway mate :)
