### ISSUE TITLE
Absorbs LuaError

### ISSUE THREAD

**Issue by rathodkanishk** [bkader/Skada-WoTLK#72]
Hey, I'm unsure of what is causing these lua errors, and I would appreciate some help.

https://imgur.com/a/onU6Qr7

I just installed the latest version (for the first time) and these errors showed up. 
I do use Details, but I have it disabled atm (trying to swap over entirely to Skada).

How do I fix this?

**Comment by bkader** [comment]
Hello. Have followed installation steps if you were using the old Skada? If you used it, please make sure to delete all traces of it.
