### ISSUE TITLE
Addon doesn't work since last commit

### ISSUE THREAD

**Issue by Pocokk** [bkader/Skada-WoTLK#73]
**Describe the bug**
 I can't select modes (damage done, healing done, threat etc) since I've installed the last update today. I have tried to delete the cache folder, no change here.
 
 here is the video about it, the bottom part is a separate window, it looks even worse than the default one (top). I don't know what went wrong. (when you see clicking, I tried do right mouse button)

https://streamable.com/441xdo

**Comment by bkader** [comment]
Can you please screenshot your addons folder as well as skada content + modules folder content

**Comment by Pocokk** [comment]
`Message: Interface\AddOns\Skada\BarDisplay.lua:623: attempt to index local 'c' (a nil value)
Time: 11/17/21 14:59:55
Count: 1
Stack: Interface\AddOns\Skada\BarDisplay.lua:623: in function `Update'
Interface\AddOns\Skada\Skada.lua:487: in function `UpdateDisplay'
Interface\AddOns\Skada\Skada.lua:2148: in function `UpdateDisplay'
Interface\AddOns\Skada\Skada.lua:692: in function `DisplaySets'
Interface\AddOns\Skada\Skada.lua:767: in function `CreateWindow'
Interface\AddOns\Skada\Skada.lua:2475: in function `ReloadSettings'
Interface\AddOns\Skada\Skada.lua:2956: in function <Interface\AddOns\Skada\Skada.lua:2952>
(tail call): ?
[C]: ?
[string "safecall Dispatcher[1]"]:9: in function <[string "safecall Dispatcher[1]"]:5>
(tail call): ?
...face\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:558: in function `EnableAddon'
...face\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:651: in function <...face\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:636>
[C]: in function `LoadAddOn'
Interface\FrameXML\UIParent.lua:235: in function `UIParentLoadAddOn'
Interface\FrameXML\UIParent.lua:258: in function `CombatLog_LoadUI'
Interface\FrameXML\UIParent.lua:482: in function <Interface\FrameXML\UIParent.lua:454>

Locals: self = <table> {
 NewBarFromPrototype = <function> defined @Interface\AddOns\Skada\Libs\SpecializedLibBars-1.0\SpecializedLibBars-1.0.lua:260
 SetDefaultModuleLibraries = <function> defined @Interface\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:398
 NewCounterBar = <function> defined @Interface\AddOns\Skada\Libs\SpecializedLibBars-1.0\SpecializedLibBars-1.0.lua:285
 GetBarGroup = <function> defined @Interface\AddOns\Skada\Libs\SpecializedLibBars-1.0\SpecializedLibBars-1.0.lua:657
 Enable = <function> defined @Interface\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:325
 NewModule = <function> defined @Interface\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:266
 ReleaseBar = <function> defined @Interface\AddOns\Skada\Libs\SpecializedLibBars-1.0\SpecializedLibBars-1.0.lua:293
 EnableModule = <function> defined @Interface\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:363
 modules = <table> {
 }
 GetModule = <function> defined @Interface\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:241
 IterateEmbeds = <function> defined @Interface\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:473
 BarClick = <function> defined @Interface\AddOns\Skada\BarDisplay.lua:414
 defaultModuleLibraries = <table> {
 }
 BarLeave = <function> defined @Interface\AddOns\Skada\BarDisplay.lua:221
 Hide = <function> defined @Interface\AddOns\Skada\BarDisplay.lua:189
 Destroy = <function> defined @Interface\AddOns\Skada\BarDisplay.lua:161
 BarEnter = <function> defined @Interface\AddOns\Skada\BarDisplay.lua:208
 GetName = <function> defined @Interface\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:310
 GetBarGroups = <function> defined @Interface\AddOns\Skada\Libs\SpecializedLibBars-1.0\SpecializedLibBars-1.0.lua:653
 defaultModuleState = true
 IsEnabled = <function> defined @Interface\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:482
 orderedModules = <table> {
 }
 SetTitle = <function> defined @Interface\AddOns\Skada\BarDisplay.lua:199
 DisableModule = <function> defined @Interface\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:381
 GetBar = <function> defined @Interface\AddOns\Skada\Libs\SpecializedLibBars-1.0\SpecializedLibBars-1.0.lua:236
 Update = <function> defined @Interface\AddOns\Skada\BarDisplay.lua:486
 baseName = "Skada"
 AddDisplayOptions = <function> defined =[C]:-1
 WindowResizing = <function> defined @Interface\AddOns\Skada\BarDisplay.lua:905
 IsModule = <function> defined @Interface\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:248
 ApplySettings = <function> defined @Interface\AddOns\Skada\BarDisplay.lua:782
 SetDefaultModuleState = <function> defined @Interface\AddOns\Skada\Libs\AceAddon-3.0\AceAddon-3.0.lua:418
 IsShown = <function> defined @Interface\AddOns\Skada\BarDisplay.lua:195
 OnMouseWheel = <function> defined @Inte`

https://imgur.com/a/a2No4ys

**Comment by bkader** [comment]
You obviously have corrupted/wrong/missing stuff in your SavedVariables, that's why you have this error. Delete all your windows and create new ones. Meanwhile, I will push a small check so people won't have the same error you had.

**Comment by Pocokk** [comment]
Thank you.

But how that happened? Just hours ago it was fine, installing the newest version shouldn't done that, no?

**Comment by bkader** [comment]
I don't know how it was caused, if you check skada defaults you will see that `textcolor` is there, and your window was missing that key for some reason, maybe you had a window using `BrokerDisplay` or something, I really don't know, unless I know what you exactly did, I mean in the settings.

**Comment by Pocokk** [comment]
I've been using the same settings/windows options since 2019, will try and update them then.

**Comment by Pocokk** [comment]
Another lua error

`Message: ...s\Skada\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:268: attempt to index local 'info' (a nil value)
Time: 11/17/21 15:48:20
Count: 2
Stack: ...s\Skada\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:268: in function <...s\Skada\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:267>
Interface\AddOns\Skada\Menus.lua:720: in function `initFunction'
...s\Skada\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:87: in function `L_UIDropDownMenu_Initialize'
...s\Skada\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:971: in function <...s\Skada\Libs\LibUIDropDownMenu\LibUIDropDownMenu.lua:833>
Interface\AddOns\Skada\Menus.lua:758: in function `ModeMenu'
Interface\AddOns\Skada\BarDisplay.lua:101: in function <Interface\AddOns\Skada\BarDisplay.lua:101>

Locals: info = nil
level = 1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index local 'info' (a nil value)"`

**Comment by bkader** [comment]
I see. So you either disabled or modules or deleted them. Otherwise, the error shouldn't have happened. Anyways, again, I implemented a quick fix so people doing that won't encounter the same error.

**Comment by Pocokk** [comment]
Thanks for the quickfix! 

Yes I did disable SOME modules because I don't use them, but didn't delete any of them manually

https://imgur.com/a/dwlOFud

This issue is very weird...
