### ISSUE TITLE
Skada power module error

### ISSUE THREAD

**Issue by Frixen** [bkader/Skada-WoTLK#74]
![image](https://user-images.githubusercontent.com/18544029/142411300-0c0e9145-3810-43d6-8d94-273329547a61.png)

**Comment by bkader** [comment]
Please make sure to reset your Skada. This error is caused by the **Total** segment being always there. Click the reset button and hold SHIFT before you accept.

**Comment by Frixen** [comment]
I reset it, the error seems to not appear anymore
