### ISSUE TITLE
Report segments from alts

### ISSUE THREAD

**Issue by dominotrix** [bkader/Skada-WoTLK#79]
With the old Skada, you could save your segments as Hunter for example and if you logged another character, you could see them and post them.

Sometimes, there is a need to show some data from a segment saved by another one of your characters (same account).

Is this possible?

**Comment by bkader** [comment]
Hello @dominotrix. Skada settings are saved per account and segments per character and this was done for a reason.
If you want to use the old Skada thing, modify the TOC file.
