### ISSUE TITLE
Does not Allow you see Details of any Rank 1 on Skada Meters.

### ISSUE THREAD

**Issue by Nezain** [bkader/Skada-WoTLK#80]
It does not allow me to View or Click to view any Details for Rank 1 on any Skada Meter Mode.

**Comment by bkader** [comment]
Hello @Nezain. Can you explain what you mean by Rank 1 please? If you could provide a screenshot it would be nice.

_Ps: if you are talking about the total segment, this was already discussed in previous issues._

**Comment by Nezain** [comment]
> Hello @Nezain. Can you explain what you mean by Rank 1 please? If you could provide a screenshot it would be nice.
> 
> _Ps: if you are talking about the total segment, this was already discussed in previous issues._

No, its not the total. For example: Top Dps is me, but I can't see my details. Like which spell did the most damage etc. But i can see Rank 2, the guy below me.

**Comment by bkader** [comment]
closing the issue for now, reopen it if the problem appears again
