### ISSUE TITLE
Some spells are not shown in "Enemy damage taken"

### ISSUE THREAD

**Issue by dominotrix** [bkader/Skada-WoTLK#81]
When I finish DBS fight, I want to see "Enemy damage taken" on adds.

If I do shift+click on the "Blood Beast" option, I see which spell did the most damage, but some spells are missing. I am SV hunter and I see no Explosive Shot while I was throwing it all the time on them.

Also I see no Starfire from boomies. Only Starfall and Wrath. I dont know if they didn't do any Starfire at all, although thats weird.

Can you check it please?

**Comment by bkader** [comment]
Hello @dominotrix. If you are using the latest version available on GitHub please make sure to increase the **Max Bars** found in window bars options. If you see the spells you can close this issue, if you don't see the spells, check if they can be seen on the **Damage** module. If none of the things mentioned above work please provide some comparison screenshots between Skada and another damager meter, only with that I can help sadly.

**Comment by dominotrix** [comment]
Hello @bkader Yes now I see my Explosive Shot <3
And Starfire too! Thank you!
