### ISSUE TITLE
Better death log

### ISSUE THREAD

**Issue by Irsont** [bkader/Skada-WoTLK#84]
scada's death log is not as convenient as Numeration, it might be worth changing it?

addon - https://www.curseforge.com/wow/addons/numeration-damage-meter/files/441731

**Comment by bkader** [comment]
- **Sequence of deaths**: Deaths module lists players deaths the death log of each death. Click enough on bars to access death logs.
- **Buffs and Debuffs** would imo an overkill and probably a useless info to hold, what's the point of showing an applied debuff if it doesn't cause death. If it causes the player's death you will see it.
- **Resurrections** is an obvious thing to see on the module. If you see a player with more than one death it means they were resurrected, so you have access to all their deaths death logs.
- **Defensive Cooldowns** a good idea but if you check death logs, bars have a red star between parenthesis meaning there was either an _overkill_, an _overheal_ OR the an amount of damage that was **absorbed**, **resisted** or **blocked**. You can tell from there if the player used a defensive cooldown or not.
