### ISSUE TITLE
Window Height not saving

### ISSUE THREAD

**Issue by Fot3k** [bkader/Skada-WoTLK#85]
**Describe the bug**
My custom window height does not save on relog and resets. I am using ElvUI with the embed to right panel. I have also tried setting them within the .lua file. I have a precise 200px height to allow for 5 bars to show in my right ElvUI panel. I also deleted the addon and all files and re-installed with the same issues. Made sure the folders and sub-folders/files are not read-only.

**To Reproduce**
1. Create new window
2. Set your bar settings, window settings etc to a precise amount to fit.
3. Relog or exit game.

**Expected behavior**
Settings should always save.

How it is when not saved - always reverts to 167px:
![image](https://user-images.githubusercontent.com/22380279/156628305-e29d764f-c50f-470e-b2f1-4b52d9bad8a5.png)
![image](https://user-images.githubusercontent.com/22380279/156628523-b9d41d6e-10e2-4f10-b506-e2dfbb46bc75.png)

How it should be - 200px height:
![image](https://user-images.githubusercontent.com/22380279/156628572-fd67ec39-62e3-4f02-b2fc-d1be28fc380c.png)
![image](https://user-images.githubusercontent.com/22380279/156628608-3967dc4a-7334-4f7c-b670-1fe2c95000dd.png)

Thanks!

**Comment by bkader** [comment]
Please make sure to either update ElvUI AddonSkins or at least update Skada skin file. Support for revisited Skada version was added a while ago.

**Comment by Fot3k** [comment]
ElvUI AddonSkins fixed the issue, thought it was latest since December 2021. Thanks!
