### ISSUE TITLE
Classic Wotlk addon version in the future?

### ISSUE THREAD

**Issue by Pocokk** [bkader/Skada-WoTLK#86]
Dear bkader, 

I've read the news about some leaked Classic WotLK files being out in the open and thus the speculations began that one day (1 year perhaps) we'll see a genuine WotLK experience from Blizzard after all these years (following Classic TBC)

I was wondering (and I know it wont happen in a day's time), do you plan to update/import this addon of yours into that version in the future? Or its too early to tell? 

I (among many others) are really immersed in your addon, using and loving it and would be really nice if can be seen in a retail environment too.

**Comment by bkader** [comment]
Hello @Pocokk 
I cannot promise to bring any of my backported or modified addons to where I never played before, retail. I can only promise that if circumstances will allow it, I will do it.
Leave this issue opened as a reminder.

**Comment by Pocokk** [comment]
Thank you for the response, will look forward to it!

**Comment by bkader** [comment]
If someone has access to classic wotlk _beta_ and can provide logs it would be great and much appreciated, it would help adapting Skada and maybe (_not sure_) some other addons.

**Comment by Pocokk** [comment]
I bet not a whole lot of people are visiting this git issue page, it would be better to try that on various discords perhaps?

**Comment by Pocokk** [comment]
Now the game is available on the PTR if you wish to check/test it.

**Comment by Pocokk** [comment]
Sorry, any update on it, have you managed to check if its possible or not?

**Comment by Pocokk** [comment]
> If someone has access to classic wotlk _beta_ and can provide logs it would be great and much appreciated, it would help adapting Skada and maybe (_not sure_) some other addons.

Sorry, any update on it? :) Have you managed to access the PTR when it was available?

**Comment by Pocokk** [comment]
I'm sad that you gave up on this project of yours, still hope one day you might be able to port it to classic!

**Comment by bkader** [comment]
I haven't really given up on this project, I just don't have access to classic, otherwise I would've ported it.

So far, it's been ported to **5.4.8** as well as **retail**, the latter was made possible because with the start edition (_or whatever its name is_) I was able to work on it and made sure it works. Only classic left and it will be whenever I get access to it.

## 9.2.7

![skada_rev_retail](https://user-images.githubusercontent.com/4732702/194142269-fc8b6ea0-4d57-43d4-a043-ca8833fe3c5b.png)

## 5.4.8

![skada_rev_mop](https://user-images.githubusercontent.com/4732702/194143935-a268f106-77b7-4283-8b96-e97405671a5a.png)

**Comment by bkader** [comment]
**Official Servers**
✔️ Dragonflight
✔️ Classic Wrath

**Private Servers**
✔️ Wrath of the Lich King
✔️ Cataclysm
✔️ Mists of Pandaria

I know it took me so long to do all these but keep in mind that what I do for one expansion I have to do it for others unless files are the same (_live ver: 1.8.78 .. dev: 1.8.83_).

Only 3 steps left and it should be ready to be released:

1. Change few modules that will hopefull reduce the amount of data recorded to the table.
2. Change the way actors (_players & enemies_) are indexes, which have some pros and cons.
3. Test everything (_especially for retail/classic versions_)

**Comment by Pocokk** [comment]
Thank you so much for your work, appreciate it and patiently waiting the end result!

**Comment by Jbsh1999** [comment]
Still no beta for wotlk classic ?

**Comment by bkader** [comment]
Over a month without touching the addon 😞 . However, I will push all changes done so far later today (01/09).
Private repositories will be made public after the push.

- [Wrath of the Lich King 3.3.5](https://github.com/bkader/Skada-WoTLK)
- [Cataclysm 4.3.4](https://github.com/bkader/Skada-Cata)
- [Mists of Pandaria 5.4.8](https://github.com/bkader/Skada-MoP)
- [Retail & Classic Wrath](https://github.com/bkader/Skada-Damage-Meter)

Issues should be reported to each repo and I will do my best to **fix** them.

**Comment by hrtyv** [comment]
Hi there, big fan of the Skada addon.

Sadly after the latest Ulduar (phase 2) update the addon does not show anylonger. 
- It seems to be loading but cant be used ingame 

Any fixes planned soon ?

**Comment by bkader** [comment]
Hello @hrtyv . I don't know what version you're using but I haven't released anything official for classic/retail at all. However, I will just push current changes and will do my best to fix any issues that may occur.
