### ISSUE TITLE
[Threat] Support for Mirror images similiar to Omen

### ISSUE THREAD

**Issue by husker3011** [bkader/Skada-WoTLK#88]
In Omen when a mage mirror images their threat goes grey but keeps calculating and showing what your actual threat is, this is extremely helpful so you know when your mirror images expire if you need to iceblock or whatever. In current skada module your threat fully disappears and you have to pray to god that once your mirror images die you're not above threat. Please add love you long time.

Visual example (vandalism is mage with mirror images up).
https://i.imgur.com/h378MsS.png

**Comment by bkader** [comment]
You don't have to pray to God or hope for anything, simply enable raw threat value in threat mode settings and you will remain on the threat window after you use mirror images. Test it and if it works you can close this issue.

**Comment by husker3011** [comment]
> You don't have to pray to God or hope for anything, simply enable raw threat value in threat mode settings and you will remain on the threat window after you use mirror images. Test it and if it works you can close this issue.

oh thats neat, thank you :*

**Comment by bkader** [comment]
Hello again @husker3011 
I am pretty sure I have added the grey bar color when **Mirror Image** or **Fade** are used, I tested it and it works and is only available if you enable `Show raw threat`. Test it and let me know.

**Comment by bkader** [comment]
Found the lines causing the bar not to turn grey when `Show raw threat` is enabled and fixed it. It will be available on the next update alongside other changes and fixes.
