### ISSUE TITLE
error in Mode child window mode

### ISSUE THREAD

**Issue by nogoodlife** [bkader/Skada-WoTLK#91]
2 windows in Mode child window mode
__ParWin (segment - boss1)
__ChildWin (segment - boss2)
Mode - **Damage**

shift+click at some Player bar to see **Damage target list**

obviously, 2 windows with 2 different segments (different bossfights) shows different target lists, so when i choose one of the enemies in Parent window (boss1) Damage target list - Child window cant find this enemy at his (boss2) Damage target list, and there is error
![image](https://user-images.githubusercontent.com/100277966/165523453-30934609-f1e3-48a9-8439-79c5edabb548.png)

other modes doesnt have this error, checked many of them (but not all, tbh)

**Comment by bkader** [comment]
Hello @nogoodlife , this error should be fixed once the fix for #90 is pushed. Thanks for reporting it.
