### ISSUE TITLE
Resourсes and Rdruid talent

### ISSUE THREAD

**Issue by Irsont** [bkader/Skada-WoTLK#93]
Hello,

now for some reason it doesn't show resource regen from druid talent [Revitalize]

only shows source talent in mana line, possibly stacked

maybe it's a server issue (wowcircle)

**Comment by bkader** [comment]
It seems to be working just fine (_data from **Warmane**_)

![Revitalize-issue#93](https://user-images.githubusercontent.com/4732702/179367677-720d0ff2-51d0-4507-b547-8bd7823f450c.png)
