### ISSUE TITLE
Return to character selection error

### ISSUE THREAD

**Issue by hubgogo** [bkader/Skada-WoTLK#94]
**Return to character selection error**

  
**inadvertent error
   When a character chooses to return to the character list in a non-hotel, an error will be reported**

The error code is as follows:

1x [ADDON_ACTION_BLOCKED] 插件 'Skada' 尝试调用保护功能 'CancelLogout()'。:
<in C code>: in function `CancelLogout'
Interface\FrameXML\StaticPopup.lua:1488: in function `OnHide':
Interface\FrameXML\StaticPopup.lua:3452: in function `StaticPopup_OnHide':
<string>:"*:OnHide":1: in function <[string "*:OnHide"]:1>
<in C code>: in function `Hide'
Interface\FrameXML\StaticPopup.lua:3286: in function `StaticPopup_Hide':
Interface\FrameXML\UIParent.lua:577: in function <Interface\FrameXML\UIParent.lua:454>:

**Only enable Skada and error collection addons**

![image](https://user-images.githubusercontent.com/91697479/185539701-4caa9643-d4ce-4c73-b9d0-30be5e40c8f4.png)

![image](https://user-images.githubusercontent.com/91697479/185539986-3d844e6a-810d-4157-b36d-39adb66d2536.png)

![2022-08-19_114315](https://user-images.githubusercontent.com/91697479/185540050-4b299b4a-ec2a-405a-b920-f92451616144.png)

![2022-08-19_114359](https://user-images.githubusercontent.com/91697479/185540068-9d3eab47-e300-4216-b0fc-cba9307b5ffe.png)

**Version: v1.8.73.359---v1.8.78
have tests
same error**

**Comment by bkader** [comment]
Hello @hubgogo 
The problem is not Skada but your game client and it is obvious just from reading the error, nothing mentioned in iy is related to Skada except the name.

**Comment by hubgogo** [comment]
Sorry, for testing, I downloaded the warmane client, and the same error was reported.
![2022-08-19_175957](https://user-images.githubusercontent.com/91697479/185597089-42f18ee7-e6a5-45fe-84ef-a793a5637aad.png)


![2022-08-19_180948](https://user-images.githubusercontent.com/91697479/185597119-be2592ff-a7f1-4dd3-bd10-b1d9f6070c4a.png)

**Comment by bkader** [comment]
Now that's a different error. Try without Skada Storage and if possible without BugSack and Buggrabber, their libs are loaded before Skada's

**Comment by hubgogo** [comment]
Hello,
After trying not to use Skada Storage, the error problem is solved
Thank you!
![2022-08-19_175957](https://user-images.githubusercontent.com/91697479/185598956-ac5e28dc-71e3-4ff4-855c-b3c8075c8613.png)

![2022-08-19_182150](https://user-images.githubusercontent.com/91697479/185598974-97bc3ead-53e6-4a5f-bd04-36b7c150e4f8.png)


![Uploading 2022-08-19_182215.png…]()

**Comment by bkader** [comment]
If you want to use storage make sure to download all 3 add-ons at the same time and when updating to update them all, sometimes changes are done to all of them.

**Comment by hubgogo** [comment]
I downloaded three files at the same time to update together

Maybe the support for Chinese is not good

The client of **warmane** I just put the Chinese file in

**Now it also reports an error without opening an account for storage**


![image](https://user-images.githubusercontent.com/91697479/185620492-54dc206b-46b8-4950-b3e5-4021f2b7ddc5.png)
