### ISSUE TITLE
Ascension - CoA class icons broken

### ISSUE THREAD

**Issue by Lionheart237** [bkader/Skada-WoTLK#96]
![image](https://user-images.githubusercontent.com/82419340/205150685-e2988a85-f1b2-46e0-9873-918250b4a8e3.png)

On Conquest of Azeroth, after updating Skada the class icons appear as fragments of base game class icons rather than the ones they were on the previous version.

**Comment by bkader** [comment]
Sorry for the long absence and reply.
Skada is available on Ascension Launcher, they have this issue probably fixed.
Don't update Skada anymore since Ascension support was dropped as of `v.1.8.78` (_on hold until I find time for it_).
