### ISSUE TITLE
Missing entry for 'GTFO Alerts'

### ISSUE THREAD

**Issue by codeduph** [bkader/Skada-WoTLK#99]
**Describe the bug**
Missing entry for 'GTFO Alerts'

Skada Damage Meter (Revisited) [1.8.84-2] (https://www.curseforge.com/wow/addons/skadarev/files/4354063)

Bugsak

1x AceLocale-3.0-6: Skada: Missing entry for 'GTFO Alerts'
[string "@Skada/Core/Functions.lua"]:33: in function <Skada/Core/Functions.lua:32>
[string "=[C]"]: ?
[string "@BlizzMove/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <BlizzMove/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@BlizzMove/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:262: in function `NewModule'
[string "@GTFO/GTFO_Skada.lua"]:25: in function `GTFO_Skada'
[string "@GTFO/GTFO.lua"]:266: in function `GTFO_OnEvent'
[string "*GTFO.xml:60_OnEvent"]:1: in function <[string "*GTFO.xml:60_OnEvent"]:1>

1x AceLocale-3.0-6: Skada: Missing entry for 'GTFO Alert Types'
[string "@Skada/Core/Functions.lua"]:33: in function <Skada/Core/Functions.lua:32>
[string "=[C]"]: ?
[string "@BlizzMove/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <BlizzMove/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@BlizzMove/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:262: in function `NewModule'
[string "@GTFO/GTFO_Skada.lua"]:26: in function `GTFO_Skada'
[string "@GTFO/GTFO.lua"]:266: in function `GTFO_OnEvent'
[string "*GTFO.xml:60_OnEvent"]:1: in function <[string "*GTFO.xml:60_OnEvent"]:1>

1x AceLocale-3.0-6: Skada: Missing entry for 'GTFO Spells'
[string "@Skada/Core/Functions.lua"]:33: in function <Skada/Core/Functions.lua:32>
[string "=[C]"]: ?
[string "@BlizzMove/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:66: in function <BlizzMove/Libs/AceAddon-3.0/AceAddon-3.0.lua:61>
[string "@BlizzMove/Libs/AceAddon-3.0-13/AceAddon-3.0.lua"]:262: in function `NewModule'
[string "@GTFO/GTFO_Skada.lua"]:27: in function `GTFO_Skada'
[string "@GTFO/GTFO.lua"]:266: in function `GTFO_OnEvent'
[string "*GTFO.xml:60_OnEvent"]:1: in function <[string "*GTFO.xml:60_OnEvent"]:1>

**Comment by bkader** [comment]
Hello @codeduph. GTFO isn't compatible with this version of Skada, only the old version. If you want to get rid of the error, please delete `GFTO_Skada.lua` from the addon folder and you should no longer see this error.
